[package]
name = "book-cli"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
rusqlite = { version = "0.32.0", features = ["bundled"] }
book_lib = { version = "0.1.2" }
